config/routes.rb
Rails.application.routes.draw do

  resources :searches
  resources :availabilities
  resources :post_attachments
	resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'password_resets/new'
  get 'password_resets/edit'

  resources :sessions
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

	resources :users
  get 'signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'index' => 'users#index'

  resources :users do
    post :coach
  end
  #=> output: user_coach POST /users/:user_id/coach(.:format)  users#coac

  root 'static_pages#home'
  get 'static_pages/home'
  get 'help' => 'static_pages#help'
  get 'mentions' => 'static_pages#mentions'
  get 'conditions' => 'static_pages#conditions'
  get 'coach' => 'static_pages#coach'
  get 'voyageur' => 'static_pages#voyageur'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :account_activations, only: [:edit]

  get 'become_coach', to: 'messages#new'
  post 'become_coach', to: 'messages#create'

  resources :posts

  resources :users do
    resources :post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message
	include ActiveModel::Model
	attr_accessor :fname, :phone, :email, :body
	validates :fname, :phone, :email, :body, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
    @user = params[:fname]
	end

	def create
    @message = Message.new message_params

    if @message.valid?
    	MessageMailer.become_coach(@message).deliver_now
      redirect_to root_url, notice: "Votre demande pour devenir coach à bien était reçu, nous vous recontacterons bientôt !"
    else
      render :new
    end
	end

	 private

  	def message_params
    	params.require(:message).permit(:fname, :phone, :email, :body)
  	end
end

app/views/messages/new.html.slim
////////////////////
// TABS PROFIL
////////////////////////////////////////////////////////////////////////////////
.tabs-wrapper.anim--cascad data-is-scroll=""


  ul.tabs__nav.anim-fade-up
    = link_to coach_path, class: 'btn btn-primary', data: {trigger_transition_page: ""} do
      span En savoir plus


  .tabs__content.anim-fade-up


    = form_for @message, url: become_coach_url do |f|
      = notice
      = @message.errors.full_messages.join(', ')

      .form-group.form-group--smooth
        = f.text_field :fname, :value => @fname, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label "Prénom", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.phone_field :phone, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label "Téléphone", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.email_field :email, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label "Email", class: 'label--smooth'

      = f.text_area :body, placeholder: 'Votre demande', rows: '5'

      = f.submit 'Envoyer', class: 'btn btn-primary'





////////////////////
// CARD RASSURANCE
////////////////////////////////////////////////////////////////////////////////
section.section--primary#scroll
  .container.anim--cascad data-is-scroll=""



    // TITLE
    // ---------------------------------------------------------
    h2.anim-fade
      div Nativing pour voyager l'esprit
      span> léger, en toute
      span.font--bold sécurité.



    // CARD
    // ---------------------------------------------------------
    .row.anim-fade.anim--cascad data-is-scroll=""


      ///// CARD 1
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/trophy-primary.svg'
            h3 Certification
          .card__content
            p
              span> Voyagez en toute sécurité, grâce à des coachs
              span.font--bold sélectionnés et certifiés par Nativing.


      ///// CARD 2
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/money-primary.svg'
            h3 Paiement
          .card__content
            p
              span> Le site web de Nativing dispose d’une fonctionnalité de paiement sécurisé
              span.font--bold pour voyager en toute tranquillité


      ///// CARD 3
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/placeholder.svg'
            h3 Adresse
          .card__content
            p
              span> Pour toute question ou demande, n’hésitez pas à
              span.font--bold contacter Nativing ou à vous déplacer directement chez nous.