config/routes.rb
Rails.application.routes.draw do

  resources :searches
  resources :availabilities
  resources :post_attachments
	resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'password_resets/new'
  get 'password_resets/edit'

  resources :sessions
  get    '/login' => 'sessions#new'
  post   '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

	resources :users
  get 'signup' => 'users#new'
  post '/signup' => 'users#create'
  get 'index' => 'users#index'

  resources :users do
    post :coach
  end
  #=> output: user_coach POST /users/:user_id/coach(.:format)  users#coac

  root 'static_pages#home'
  get 'static_pages/home'
  get 'help' => 'static_pages#help'
  get 'mentions' => 'static_pages#mentions'
  get 'conditions' => 'static_pages#conditions'
  get 'coach' => 'static_pages#coach'
  get 'voyageur' => 'static_pages#voyageur'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :account_activations, only: [:edit]

  get 'become_coach', to: 'messages#new'
  post 'become_coach', to: 'messages#create'

  resources :posts

  resources :users do
    resources :post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" },

                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_and_belongs_to_many :spoken_languages
  # Add a virtual field named `address` and a class method `address_fields` returning `JT::Rails::Address.fields` prefixed by `address_` in this case
  has_address :address
  has_one :post
  has_many :availabilities

  include Filterable

  before_save   :downcase_email
  before_create :create_activation_digest
	validates :fname, presence: true, length: { maximum: 50 }
	validates :lname, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
			  		  format: { with: VALID_EMAIL_REGEX },
			          uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  filterrific(
    default_filter_params: {},
    available_filters: [
      :with_mother_tongue,
      :with_locality,
      :with_start_time_gte
    ]
  )

  scope :with_mother_tongue, -> (search_string) {
  where("users.mother_tongue LIKE ?", (search_string.to_s.gsub('*', '%') + '%').gsub(/%+/, '%'))
  }

  scope :with_locality, -> (search_string) {
    where("users.locality LIKE ?", (search_string.to_s.gsub('*', '%') + '%').gsub(/%+/, '%'))
  }

  scope :with_start_time_gte, -> (ref_date) { joins(:availabilities).where('availabilities.start_time >= ?', ref_date) }

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

   # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def age
    ((Time.zone.now - birthdate.to_i) / 1.year.seconds rescue 25).floor
  end

  def self.apply_filters(params)
    user = self
    user = user_by_mother_tongue(mother_tongue: params[:mother_tongue]) if params[:mother_tongue].present?
    user = user_by_locality(locality: params[:locality]) if params[:locality].present?
    user
  end


  private

     # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def first; end
  def second; end
  def third; end

  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Merci de consulter vos mails et de cliquer sur le lien d'activation."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @availabilities = Availability.all
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profil mis à jour"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @filterrific = initialize_filterrific(
      User,
      params[:filterrific]
      #persistence_id: 'shared_key',
      #default_filter_params: {},
      #available_filters: [],
    ) or return
    @users = @filterrific.find.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end

    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      puts "Had to reset filterrific params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprimé"
    redirect_to users_url
  end

  def coach
    user = User.find(params[:user_id])
    user.update(coach: params[:coach])
    redirect_to users_url
  end

  def start_time
    self.my_related_model.start ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end

  private

    def user_params
      params.require(:user).permit(:fname, :lname, :email, :password,
                                   :password_confirmation, :photo, :birthdate, :mother_tongue, :coach, :phone, :street_number, :locality, :route, :administrativearea_level_1, :country, :postal_code, spoken_language_ids:[])
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Merci de vous connecter."
        redirect_to login_url
      end
    end
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.slim
div#filterrific_results

  / <!-- <div>
  /   <%= page_entries_info users %>
  / </div> -->

  .row
    - @users.each do |user|
    	- if user.coach?
          .col-sm-4
            .thumb.thumb--profile
              = link_to "", class: 'thumb__image', data: {trigger_transition_page: ""} do
                = image_tag "missing.png", class: 'img-cover'
              = link_to "", class: 'thumb__title link-gray-primary', data: {trigger_transition_page: ""} do
                span> = user.fname
                span> = user.lname
              .thumb__speciality = user.mother_tongue
              .thumb__location
                span>
                  = image_tag 'icons/placeholder.svg'
                span> = user.postal_code
                span> = user.locality

              = link_to "http://localhost:3000/posts/1", class: 'btn btn-primary', data: {trigger_transition_page: ""} do
                span Voir le profil
              = link_to "", class: 'thumb__favorite' do
                i.material-icons favorite


  = will_paginate users

app/views/users/_user.html.erb
<div id="filterrific_results">
  <% @users.each do |user| %>
    <li>
    	<%= link_to image_tag(user.photo.url(:thumb)), user %>
        | <%= link_to user.fname + ' ' + user.lname, user %>
        | <%= user.email %>

        <% if current_user.admin? && !current_user?(user) %>
        	 <% if user.coach %>
        | <%= link_to "Retirer des coachs", user_coach_path(user, coach: false), method: :post,
                                      data: { confirm: "Êtes vous sûr ?" } %>
        | <%= link_to "Voir son annonce", user.post %>
            <% else %>
        | <%= link_to "Passer coach", user_coach_path(user, coach: true), method: :post, 
                                      data: { confirm: "Êtes vous sûr ?" } %>
            <% end %>
        | <%= link_to "Supprimer", user, method: :delete,
                                      data: { confirm: "Êtes vous sûr ?" } %>
        <% end %>
    </li>
  <% end %>
</div>

app/views/users/edit.html.slim
////////////////////
// TABS PARAMETRE
////////////////////////////////////////////////////////////////////////////////
.tabs-wrapper#tabs.anim--cascad data-is-scroll=""


  ul.tabs__nav.anim-fade-up
    li
      = link_to "Paramètres voyageur", "#tabs-1", class: 'link-white-primary'
    li
      = link_to "Paramètres coach", "#tabs-2", class: 'link-white-primary'
    li
      = link_to "Disponibilités", "#tabs-3", class: 'link-white-primary'


  .tabs__content.anim-fade-up#tabs-1

    h1 Paramètres voyageur

    = form_for (@user), :html => { :multipart => true } do |f|

      = f.label :photo, "Photo :"
      = f.file_field :photo, class: 'form-control'

      .form-group.form-group--smooth
        = f.text_field :fname, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :fname , "Prénom :", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :lname, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :lname, "Nom :", class: 'label--smooth'

      = f.label :birthdate, "Date de naissance :"
      = f.date_select :birthdate, class: 'form-control', data: { is_input_smooth: ''}

      .form-group.form-group--smooth
        = f.text_field :mother_tongue, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :mother_tongue, "Langue maternelle :", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :spoken_language_ids, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :spoken_language_ids, "Autres langues parlées :", class: 'label--smooth'

      / = f.label :spoken_language_ids, "Autres langues parlées :"
      / = f.collection_check_boxes :spoken_language_ids, SpokenLanguage.all, :id, :name do |b|
      /   .collection-check-box
      /     = b.check_box
      /     = b.label

      .form-group.form-group--smooth
        = f.email_field :email, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :email, "Email :", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.password_field :password, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :password, "Mot de passe :", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.password_field :password_confirmation, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :password_confirmation, "Confirmation", class: 'label--smooth'

      = f.submit "Enregistrer les changements", class: "btn btn-primary"


  .tabs__content.anim-fade-up#tabs-2

    h1 Paramètres coach

    = form_for (@user), :html => { :multipart => true } do |f|

      .form-group.form-group--smooth
        = f.phone_field :phone, class: 'form-control', data: { is_input_smooth: ''}
        = f.label :phone, "Téléphone :", class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :address, id: :autocomplete_address, class: 'form-control', data: { is_input_smooth: ''}

      .form-group.form-group--smooth
        = f.number_field :street_number, id: :street_number, class: 'form-control', data: { is_input_smooth: ''}
        = f.label 'N° de voie', class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :route, id: :route, class: 'form-control', data: { is_input_smooth: ''}
        = f.label 'Nom de la voie', class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :locality, id: :locality, class: 'form-control', data: { is_input_smooth: ''}
        = f.label 'Ville', class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :administrative_area_level_1, id: :administrative_area_level_1, class: 'form-control', data: { is_input_smooth: ''}
        = f.label 'Région', class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :country, id: :country, class: 'form-control', data: { is_input_smooth: ''}
        = f.label 'Pays', class: 'label--smooth'

      .form-group.form-group--smooth
        = f.number_field :postal_code, id: :postal_code, class: 'form-control', data: { is_input_smooth: ''}
        = f.label 'Code postal', class: 'label--smooth'

      = f.submit "Enregistrer les changements", class: "btn btn-primary"


  .tabs__content.anim-fade-up#tabs-3

    h1 Disponiblités

    = month_calendar events: @availabilities do |date, availabilities|
      = date.day

    / availabilities.each do |availability|

    /   = availability.name
    /   = link_to "Editer", edit_availability_path(availability)

    div.btn-wrapper
      span
        = link_to availabilities_path, class: 'btn btn-primary btn-outline', data: {trigger_transition_page: ""} do
          span Voir toutes les disponibilités
      span
        = link_to new_availability_path, class: 'btn btn-primary', data: {trigger_transition_page: ""} do
          span Ajouter une disponibilité



////////////////////
// CARD RASSURANCE
////////////////////////////////////////////////////////////////////////////////
section.section--primary#scroll
  .container.anim--cascad data-is-scroll=""



    // TITLE
    // ---------------------------------------------------------
    h2.anim-fade
      div Nativing pour voyager l'esprit
      span> léger, en toute
      span.font--bold sécurité.



    // CARD
    // ---------------------------------------------------------
    .row.anim-fade.anim--cascad data-is-scroll=""


      ///// CARD 1
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/trophy-primary.svg'
            h3 Certification
          .card__content
            p
              span> Voyagez en toute sécurité, grâce à des coachs
              span.font--bold sélectionnés et certifiés par Nativing.


      ///// CARD 2
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/money-primary.svg'
            h3 Paiement
          .card__content
            p
              span> Le site web de Nativing dispose d’une fonctionnalité de paiement sécurisé
              span.font--bold pour voyager en toute tranquillité


      ///// CARD 3
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/placeholder.svg'
            h3 Adresse
          .card__content
            p
              span> Pour toute question ou demande, n’hésitez pas à
              span.font--bold contacter Nativing ou à vous déplacer directement chez nous.


javascript:
  $(document).ready(function() {
      $("#tabs").tabs();
  });

app/views/users/index.html.slim
section.section--user

  ////////////////////
  // HERO SMALL
  ////////////////////////////////////////////////////////////////////////////////
  .hero.hero--sm



    // HERO IMAGE
    // ---------------------------------------------------------
    .hero__image data-is-scroll=""
      = image_tag "home/slider-3.jpg", class: 'img-cover'


    // HERO CONTENT
    // ---------------------------------------------------------
    .hero__content data-is-scroll=""
      .container
        .hero__title.anim--cascad data-is-scroll=""
          h1.anim-fade-up Partez ou vous voulez, quand vous voulez.

          p.anim-fade-up Nos hôtes Nativing vous accueillent chez eux, partout en France.

          = form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit', class: 'searchbar anim-fade-up'} do |f|

            .form-group.form-group--smooth
              = f.text_field :with_mother_tongue, class: 'mother_tongue filterrific-periodically-observed form-control input-smooth--first input-smooth', data: { is_input_smooth: ''}
              = f.label "Langue", class: 'label--smooth'

            .form-group.form-group--smooth
              = f.text_field :with_locality, class: 'locality filterrific-periodically-observed form-control input-smooth', data: { is_input_smooth: ''}
              = f.label "Ville", class: 'label--smooth'

            .form-group.form-group--smooth.input-smooth--last
              = f.text_field :with_start_time_gte, 'data-provide' => 'datepicker', class: 'form-control input-smooth', data: { is_input_smooth: ''}
              = f.label "Date", class: 'label--smooth'

            = f.submit 'Rechercher', class: 'btn btn-primary'





  ////////////////////
  // RASSURANCE
  ////////////////////////////////////////////////////////////////////////////////
  section.section--cards
    .container
      .row.anim--cascad data-is-scroll=""
        .col-sm-4.anim-fade-up
          .card.card--rassurance
            .card__title
              = image_tag 'icons/trophy-primary.svg'
              h4 Confiance
            .card__content
              span> Voyagez partout en France et progressez en langue en toute sécurité, grâce à nos hôtes
              span.font--bold sélectionnés et certifiés par Nativing.
        .col-sm-4.anim-fade-up
          .card.card--rassurance
            .card__title
              = image_tag 'icons/money-primary.svg'
              h4 Prix
            .card__content
              span> Nativing vous permet de voyager à prix réduit, en séjournant chez des hôtes natifs.
              span.font--bold en séjournant chez des hôtes natifs.
        .col-sm-4.anim-fade-up
          .card.card--rassurance
            .card__title
              = image_tag 'icons/placeholder.svg'
              h4 Localisation
            .card__content
              span> Nativing vous offre la possibilité d’apprendre une langue dans le monde entier.
              span.font--bold d’apprendre une langue et de voyager dans le monde entier.





  ////////////////////
  // LISTE USERS
  ////////////////////////////////////////////////////////////////////////////////
  section.section--users
    .container
      / = link_to 'Reset filters', reset_filterrific_url

      = render_filterrific_spinner

      = render partial: 'users/list', locals: { users: @users }

////////////////////
// CARD RASSURANCE
////////////////////////////////////////////////////////////////////////////////
section.section--primary#scroll
  .container.anim--cascad data-is-scroll=""



    // TITLE
    // ---------------------------------------------------------
    h2.anim-fade
      div Nativing pour voyager l'esprit
      span> léger, en toute
      span.font--bold sécurité.



    // CARD
    // ---------------------------------------------------------
    .row.anim-fade.anim--cascad data-is-scroll=""


      ///// CARD 1
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/trophy-primary.svg'
            h3 Certification
          .card__content
            p
              span> Voyagez en toute sécurité, grâce à des coachs
              span.font--bold sélectionnés et certifiés par Nativing.


      ///// CARD 2
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/money-primary.svg'
            h3 Paiement
          .card__content
            p
              span> Le site web de Nativing dispose d’une fonctionnalité de paiement sécurisé
              span.font--bold pour voyager en toute tranquillité


      ///// CARD 3
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/placeholder.svg'
            h3 Adresse
          .card__content
            p
              span> Pour toute question ou demande, n’hésitez pas à
              span.font--bold contacter Nativing ou à vous déplacer directement chez nous.


javascript:
  $('[data-behaviour~=datepicker]').datepicker();

app/views/users/index.js.erb
<% js = escape_javascript(
  render(partial: 'users/list', locals: { users: @users })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/users/new.html.slim
section.section--session


  .section__image
    = image_tag 'home/slider-2.jpg', class: 'img-cover'


  .section__content.anim-fade-up data-is-scroll=""


    = form_for(@user, url: signup_path) do |f|

      h1.text-left Inscription

      .form-group.form-group--smooth
        = f.text_field :fname, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label :Prénom, class: 'label--smooth'

      .form-group.form-group--smooth
        = f.text_field :lname, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label :Nom, class: 'label--smooth'

      .form-group.form-group--smooth
        = f.email_field :email, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label :Email, class: 'label--smooth'

      .form-group.form-group--smooth
        = f.password_field :password, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label :Mot_de_passe, class: 'label--smooth'

      .form-group.form-group--smooth
        = f.password_field :password_confirmation, class: 'form-control input-smooth', data: { is_input_smooth: ''}
        = f.label :Confirmation_mot_de_passe, "Confirmation", class: 'label--smooth'

      = f.submit "Créer mon compte", class: "btn btn-primary"

    = link_to login_path, class: 'btn btn-block btn-secondary new-account', data: {trigger_transition_page: ""} do
      span Se connecter


  .section__description.anim-fade-up data-is-scroll=""
    h2 Nativing, expérimentez l'immersion.
    p Avec Nativing, faites le choix de l’immersion pour découvrir un pays et apprendre sa langue.

app/views/users/show.html.slim
////////////////////
// TABS PROFIL
////////////////////////////////////////////////////////////////////////////////
.tabs-wrapper#tabs.anim--cascad data-is-scroll=""


  ul.tabs__nav.anim-fade-up
    li
      = link_to "Profil voyageur", "#tabs-1", class: 'link-white-primary'
    li
      = link_to "Profil coach", "#tabs-2", class: 'link-white-primary'


  .tabs__content.anim-fade-up#tabs-1
    h1 Profil voyageur
    aside
      section.user_info.anim--cascad data-is-scroll=""
        .tabs__picture.anim-fade-up
          = image_tag(@user.photo.url(:thumb))
          h3
            span> = @user.fname
            span> = @user.lname
            - if @user.coach
              div.speciality> Coach
        p.anim-fade-up
          span.user__info__title> Adresse email :
          span> = @user.email
        p.anim-fade-up
          span.user__info__title> Langue maternelle :
          span> = @user.mother_tongue
        p.anim-fade-up
          span.user__info__title> Autres langues parlées :
          span> = @user.spoken_languages.map(&:name).sort.join(", ")
        = link_to edit_user_path(current_user), class: 'btn btn-primary', data: {trigger_transition_page: ""} do
          span Editer le profil


  .tabs__content.anim-fade-up#tabs-2
    h1 Profil coach
    aside
      section.user_info
        .tabs__picture.anim-fade-up
          = image_tag(@user.photo.url(:thumb))
          h3
            span> = @user.fname
            span> = @user.lname
            - if @user.coach
              div.speciality> Coach
        p
          span.user__info__title> Numéro de téléphone :
          span> = @user.phone
        p
          span.user__info__title> Adresse :
        p
          span> = @user.street_number
          span> = @user.route
        p
          span> = @user.postal_code
          span> = @user.locality
        p
          span> = @user.country
        = link_to edit_user_path(current_user), class: 'btn btn-primary', data: {trigger_transition_page: ""} do
          span Editer le profil






////////////////////
// CARD RASSURANCE
////////////////////////////////////////////////////////////////////////////////
section.section--primary#scroll
  .container.anim--cascad data-is-scroll=""



    // TITLE
    // ---------------------------------------------------------
    h2.anim-fade
      div Nativing pour voyager l'esprit
      span> léger, en toute
      span.font--bold sécurité.



    // CARD
    // ---------------------------------------------------------
    .row.anim-fade.anim--cascad data-is-scroll=""


      ///// CARD 1
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/trophy-primary.svg'
            h3 Certification
          .card__content
            p
              span> Voyagez en toute sécurité, grâce à des coachs
              span.font--bold sélectionnés et certifiés par Nativing.


      ///// CARD 2
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/money-primary.svg'
            h3 Paiement
          .card__content
            p
              span> Le site web de Nativing dispose d’une fonctionnalité de paiement sécurisé
              span.font--bold pour voyager en toute tranquillité


      ///// CARD 3
      .col-sm-4.anim-fade-up
        .card.card--dot
          .card__title
            .card__dot
              = image_tag 'icons/placeholder.svg'
            h3 Adresse
          .card__content
            p
              span> Pour toute question ou demande, n’hésitez pas à
              span.font--bold contacter Nativing ou à vous déplacer directement chez nous.





javascript:
  $(document).ready(function() {
      $("#tabs").tabs();
  });